[FIX] sale_exception_credit_limit: error en runbot al crear nueva factura Ticket: 74964
El bug se produjo a partir de este cambio de parte de Odoo https://github.com/odoo/odoo/commit/b5d02cc72543b36c7e5e620a3a579f15c88baed6#diff-1e3bd6be3bfb83a37ec9fb800ce8b1c95afe0be90ff792874ae7299c320a2f6e

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/http.py", line 1770, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/http.py", line 1797, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/http.py", line 2001, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/data/build/adhoc-cicd-odoo-odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/data/build/adhoc-cicd-odoo-odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/data/build/adhoc-cicd-odoo-odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/adhoc-cicd-odoo-odoo/addons/account/models/account_move.py", line 2606, in onchange
    return super().onchange(values, field_names, fields_spec)
  File "/data/build/adhoc-cicd-odoo-odoo/addons/web/models/models.py", line 1077, in onchange
    snapshot1 = RecordSnapshot(record, fields_spec)
  File "/data/build/adhoc-cicd-odoo-odoo/addons/web/models/models.py", line 1164, in __init__
    self.fetch(name)
  File "/data/build/adhoc-cicd-odoo-odoo/addons/web/models/models.py", line 1179, in fetch
    self[field_name] = self.record[field_name]
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/models.py", line 6603, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/fields.py", line 1207, in __get__
    self.compute_value(recs)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/fields.py", line 1389, in compute_value
    records._compute_field_value(self)
  File "/data/build/adhoc-cicd-odoo-odoo/addons/mail/models/mail_thread.py", line 424, in _compute_field_value
    return super()._compute_field_value(field)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/models.py", line 4875, in _compute_field_value
    fields.determine(field.compute, self)
  File "/data/build/adhoc-cicd-odoo-odoo/odoo/fields.py", line 102, in determine
    return needle(*args)
  File "/data/build/adhoc-cicd-odoo-odoo/addons/account/models/account_move.py", line 1488, in _compute_partner_credit_warning
    move.partner_credit_warning = self._build_credit_warning_message(
TypeError: AccountMove._build_credit_warning_message() got an unexpected keyword argument 'exclude_amount'

The above server error caused the following client error:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://53388-17-0-all.runbot.adhoc.com.ar/web/assets/66d609c/web.assets_web.min.js:916:101)
    at App.handleError (https://53388-17-0-all.runbot.adhoc.com.ar/web/assets/66d609c/web.assets_web.min.js:1542:29)
    at ComponentNode.initiateRender (https://53388-17-0-all.runbot.adhoc.com.ar/web/assets/66d609c/web.assets_web.min.js:1006:19)

Caused by: RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://53388-17-0-all.runbot.adhoc.com.ar/web/assets/66d609c/web.assets_web.min.js:2870:163)
    at XMLHttpRequest.<anonymous> (https://53388-17-0-all.runbot.adhoc.com.ar/web/assets/66d609c/web.assets_web.min.js:2874:13)