Cherry pick of a3d44138dd5c9b96abea7542a4e27bdcece03851 failed
stdout:
Auto-merging sale_gathering/views/sale_order_views.xml
Auto-merging sale_gathering/__manifest__.py
CONFLICT (content): Merge conflict in sale_gathering/__manifest__.py

stderr:
19:07:32.227700 git.c:444               trace: built-in: git cherry-pick a3d44138dd5c9b96abea7542a4e27bdcece03851
error: could not apply a3d44138... [IMP] sale_gathreing: add fields in quotation report
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: