Cherry pick of 074ba8e0ca7699e118e234247bf2fdbe472769ae failed
stdout:
Auto-merging pos_ux/views/pos_session_view.xml
Auto-merging pos_ux/__manifest__.py
CONFLICT (content): Merge conflict in pos_ux/__manifest__.py

stderr:
16:20:49.937408 git.c:444               trace: built-in: git cherry-pick 074ba8e0ca7699e118e234247bf2fdbe472769ae
error: could not apply 074ba8e0... [REF] pos_ux: intermediary account is required
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: