Cherry pick of f115afa023232ae259629e7cc79c50c32e04d9ed failed
stdout:
Auto-merging sale_stock_ux/views/sale_order_views.xml
Auto-merging sale_stock_ux/__manifest__.py
CONFLICT (content): Merge conflict in sale_stock_ux/__manifest__.py

stderr:
14:24:26.949682 git.c:444               trace: built-in: git cherry-pick f115afa023232ae259629e7cc79c50c32e04d9ed
error: could not apply f115afa0... moved 'delivery_status' after 'invoice_status' on tree view
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: